### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by kevtheskin** [frostmar/rtl433-webmon#1]
Hello there, For a linux noobie can you please tell me how to get this working  in ubuntu 18.4 bionic. Thanks Kev

**Comment by frostmar** [comment]
Thanks for the interest, but this is a hobby project for my own use and might not be very consumable for others - especially if you don't have much experience with Linux or basic programming.

I've added some basic setup info to the readme, to give a starting point if you want to try it out.
